[package]
name = "get-started-wasm"
version = "0.0.0"
authors = ["nju33 <nju33.ki@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.60"

[profile.release]
opt-level = "s"
